/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import despensa.Producto;
import despensa.transactions.GetAll;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gottig
 */
public class IndexFrame extends javax.swing.JFrame {

    /**
     * Creates new form IndexFrame
     */
    public IndexFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTabIndex = new javax.swing.JPanel();
        jButtonIndexExit = new javax.swing.JButton();
        jTitleIndexWelcome = new javax.swing.JTextField();
        jPanelTabSearch = new javax.swing.JPanel();
        jPanelTabCreate = new javax.swing.JPanel();
        jPanelTabDelete = new javax.swing.JPanel();
        jPanelTabShowAll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOfAll = new javax.swing.JTable();
        jMainTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 70));
        setPreferredSize(new java.awt.Dimension(820, 640));

        jPanelBase.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelBase.setMinimumSize(new java.awt.Dimension(820, 640));
        jPanelBase.setPreferredSize(new java.awt.Dimension(820, 640));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N

        jPanelTabIndex.setBackground(new java.awt.Color(231, 227, 227));

        jButtonIndexExit.setBackground(new java.awt.Color(153, 153, 153));
        jButtonIndexExit.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButtonIndexExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIndexExit.setText("Salir");
        jButtonIndexExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndexExitActionPerformed(evt);
            }
        });

        jTitleIndexWelcome.setBackground(new java.awt.Color(204, 204, 255));
        jTitleIndexWelcome.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jTitleIndexWelcome.setForeground(new java.awt.Color(0, 153, 0));
        jTitleIndexWelcome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTitleIndexWelcome.setText("Gestión de Productos");
        jTitleIndexWelcome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)));

        javax.swing.GroupLayout jPanelTabIndexLayout = new javax.swing.GroupLayout(jPanelTabIndex);
        jPanelTabIndex.setLayout(jPanelTabIndexLayout);
        jPanelTabIndexLayout.setHorizontalGroup(
            jPanelTabIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabIndexLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(jPanelTabIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabIndexLayout.createSequentialGroup()
                        .addComponent(jTitleIndexWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabIndexLayout.createSequentialGroup()
                        .addComponent(jButtonIndexExit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(351, 351, 351))))
        );
        jPanelTabIndexLayout.setVerticalGroup(
            jPanelTabIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabIndexLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jTitleIndexWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButtonIndexExit)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanelTabIndex);

        javax.swing.GroupLayout jPanelTabSearchLayout = new javax.swing.GroupLayout(jPanelTabSearch);
        jPanelTabSearch.setLayout(jPanelTabSearchLayout);
        jPanelTabSearchLayout.setHorizontalGroup(
            jPanelTabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanelTabSearchLayout.setVerticalGroup(
            jPanelTabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar", jPanelTabSearch);

        javax.swing.GroupLayout jPanelTabCreateLayout = new javax.swing.GroupLayout(jPanelTabCreate);
        jPanelTabCreate.setLayout(jPanelTabCreateLayout);
        jPanelTabCreateLayout.setHorizontalGroup(
            jPanelTabCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanelTabCreateLayout.setVerticalGroup(
            jPanelTabCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crear Nuevo", jPanelTabCreate);

        javax.swing.GroupLayout jPanelTabDeleteLayout = new javax.swing.GroupLayout(jPanelTabDelete);
        jPanelTabDelete.setLayout(jPanelTabDeleteLayout);
        jPanelTabDeleteLayout.setHorizontalGroup(
            jPanelTabDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanelTabDeleteLayout.setVerticalGroup(
            jPanelTabDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Borrar", jPanelTabDelete);

        jTableOfAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Marca", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOfAll.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTableOfAllComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOfAll);

        javax.swing.GroupLayout jPanelTabShowAllLayout = new javax.swing.GroupLayout(jPanelTabShowAll);
        jPanelTabShowAll.setLayout(jPanelTabShowAllLayout);
        jPanelTabShowAllLayout.setHorizontalGroup(
            jPanelTabShowAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabShowAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTabShowAllLayout.setVerticalGroup(
            jPanelTabShowAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabShowAllLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mostrar Todos", jPanelTabShowAll);

        jPanelBase.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 820, 600));

        jMainTitle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMainTitle.setText("Productos");
        jMainTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N
        jPanelBase.add(jMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIndexExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndexExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonIndexExitActionPerformed

    private void jTableOfAllComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTableOfAllComponentAdded
        List<Producto> array = new ArrayList<>();
        //Producto producto = new Producto();
        GetAll productos = new GetAll();
        
        DefaultTableModel modelo = new DefaultTableModel();
        jTableOfAll.setModel(modelo);
        array = productos.getAll();
        Object[] toArray = array.toArray();
        for (Object arr: toArray) {
            modelo.addRow(toArray);
        }
    }//GEN-LAST:event_jTableOfAllComponentAdded

    /**
     * @param args the command line arguments
     */
    // PARA USAR FRAME USAR ESTE MAIN
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IndexFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIndexExit;
    private javax.swing.JLabel jMainTitle;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelTabCreate;
    private javax.swing.JPanel jPanelTabDelete;
    private javax.swing.JPanel jPanelTabIndex;
    private javax.swing.JPanel jPanelTabSearch;
    private javax.swing.JPanel jPanelTabShowAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOfAll;
    private javax.swing.JTextField jTitleIndexWelcome;
    // End of variables declaration//GEN-END:variables
}
